name: ridehailing-pudo
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - geopandas
  - shapely>=2
  - pyproj
  - fiona
  - rtree
  - libspatialindex
  - folium
  - branca
  - scikit-learn
  - pulp
  - sqlalchemy
  - psycopg2-binary
  - python-dotenv
  - libpysal
  - esda
  - pip:
      - streamlit>=1.31
      - streamlit-folium>=0.20
