name: ridehailing-pudo
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  # core scientific
  - numpy
  - pandas>=2.2
  # geospatial (pin agar stabil di cloud)
  - shapely>=2.0,<2.1
  - pyproj>=3.6,<3.7
  - rtree>=1.2
  - libspatialindex
  - geopandas>=0.14,<1.0
  # I/O geospatial: pilih salah satu jalur
  - pyogrio>=0.9         # jalur modern (disarankan)
  # - fiona>=1.9,<1.10   # kalau kamu butuh Fiona, aktifkan ini
  # - gdal>=3.8,<3.9     # hanya jika pakai Fiona; cocokkan versinya
  # viz / ML / utils
  - folium
  - branca
  - scikit-learn
  - pulp
  - sqlalchemy
  - psycopg2             # bukan psycopg2-binary
  - python-dotenv
  - libpysal
  - esda
  - pip:
      - streamlit>=1.31
      - streamlit-folium>=0.20
